// frontend/src/components/container.tsx
import { HTMLAttributes, forwardRef } from "react";
import { cn } from "../lib/cn";

export const Container = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => (
	<div ref={ref} className={cn("rounded-box overflow-x-auto bg-base-100 p-6", className)} {...props} />
));

Container.displayName = "Container";

// solid/src/components/ui/container.tsx
import { JSX, ParentComponent } from "solid-js";

import { classListToClassValues, cn } from "../../lib/cn";

export const Container: ParentComponent<JSX.HTMLAttributes<HTMLDivElement>> = (properties) => (
	<div
		{...properties}
		class={cn(
			"rounded-box overflow-x-auto bg-base-100 p-6",
			properties.class,
			classListToClassValues(properties.classList),
		)}
		classList={undefined}
	/>
);
