// frontend/src/components/form-buttons.tsx
import { HTMLAttributes, forwardRef } from "react";
import { cn } from "../lib/cn";

export const FormButtons = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
	({ className, ...props }, ref) => (
		<div ref={ref} className={cn("float-right flex space-x-2 pt-4", className)} {...props} />
	),
);

FormButtons.displayName = "FormButtons";

// solid/src/components/ui/form-buttons.tsx
import { JSX, ParentComponent } from "solid-js";

import { classListToClassValues, cn } from "../../lib/cn";

export const FormButtons: ParentComponent<JSX.HTMLAttributes<HTMLDivElement>> = (properties) => (
	<div
		{...properties}
		class={cn("float-right flex space-x-2 pt-4", properties.class, classListToClassValues(properties.classList))}
		classList={undefined}
	/>
);
